"""variaveis_template_fontes

Revision ID: 3ac8de259402
Revises: 364478fd9506
Create Date: 2026-09-21 23:26:55.434985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ac8de259402'
down_revision: Union[str, None] = '364478fd9506'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faixa_variable_mappings', sa.Column('fonte_tipo', sa.String(), server_default='coluna', nullable=False))
    op.add_column('faixa_variable_mappings', sa.Column('expressao', sa.String(), nullable=True))
    op.alter_column('faixa_variable_mappings', 'column_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # Preenche column_name nulo caso existam mapeamentos de expressao antes de reverter a nulabilidade
    op.execute("UPDATE faixa_variable_mappings SET column_name = '' WHERE column_name IS NULL")
    op.alter_column('faixa_variable_mappings', 'column_name',
               existing_type=sa.String(),
               nullable=False)
    op.drop_column('faixa_variable_mappings', 'expressao')
    op.drop_column('faixa_variable_mappings', 'fonte_tipo')
    # ### end Alembic commands ###
