"""baseline: schema atual

Revision ID: 3bd1d89aa92f
Revises: 
Create Date: 2026-09-19 02:44:49.620048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bd1d89aa92f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('meta_template_name', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('header_type', sa.Enum('none', 'image', name='templateheadertype'), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'pending', 'approved', 'rejected', name='templatestatus'), nullable=False),
    sa.Column('meta_status_raw', sa.String(), nullable=True),
    sa.Column('meta_template_id', sa.String(), nullable=True),
    sa.Column('waba_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_templates_name'), 'templates', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('whatsapp_numbers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('waba_id', sa.String(), nullable=False),
    sa.Column('phone_number_id', sa.String(), nullable=False),
    sa.Column('display_phone_number', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_numbers_phone_number_id'), 'whatsapp_numbers', ['phone_number_id'], unique=True)
    op.create_index(op.f('ix_whatsapp_numbers_waba_id'), 'whatsapp_numbers', ['waba_id'], unique=False)
    op.create_table('faixas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_number_index', sa.Integer(), nullable=False),
    sa.Column('upload_field_mapping', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faixas_name'), 'faixas', ['name'], unique=True)
    op.create_table('template_variables',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('internal_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'position')
    )
    op.create_table('cobranca_fila',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('faixa_id', sa.String(), nullable=False),
    sa.Column('codigo_cliente', sa.String(), nullable=False),
    sa.Column('codigo_tipo', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('valor', sa.String(), nullable=True),
    sa.Column('celular', sa.String(), nullable=False),
    sa.Column('celular_original', sa.String(), nullable=False),
    sa.Column('variables_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'reserved', 'sent', 'error', 'invalid_phone', name='queuestatus'), nullable=False),
    sa.Column('whatsapp_number_id', sa.String(), nullable=True),
    sa.Column('whatsapp_message_id', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('reserved_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['faixa_id'], ['faixas.id'], ),
    sa.ForeignKeyConstraint(['whatsapp_number_id'], ['whatsapp_numbers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cobranca_fila_celular'), 'cobranca_fila', ['celular'], unique=False)
    op.create_index(op.f('ix_cobranca_fila_codigo_cliente'), 'cobranca_fila', ['codigo_cliente'], unique=False)
    op.create_index(op.f('ix_cobranca_fila_faixa_id'), 'cobranca_fila', ['faixa_id'], unique=False)
    op.create_index(op.f('ix_cobranca_fila_status'), 'cobranca_fila', ['status'], unique=False)
    op.create_table('dispatch_configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('faixa_id', sa.String(), nullable=False),
    sa.Column('interval_seconds', sa.Integer(), nullable=False),
    sa.Column('batch_size', sa.Integer(), nullable=False),
    sa.Column('schedule_days', sa.String(), nullable=False),
    sa.Column('schedule_start', sa.String(), nullable=False),
    sa.Column('schedule_end', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('force_run', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['faixa_id'], ['faixas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('faixa_id')
    )
    op.create_table('faixa_numbers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('faixa_id', sa.String(), nullable=False),
    sa.Column('whatsapp_number_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['faixa_id'], ['faixas.id'], ),
    sa.ForeignKeyConstraint(['whatsapp_number_id'], ['whatsapp_numbers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('faixa_id', 'whatsapp_number_id')
    )
    op.create_table('faixa_variable_mappings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('faixa_id', sa.String(), nullable=False),
    sa.Column('template_variable_id', sa.String(), nullable=False),
    sa.Column('column_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['faixa_id'], ['faixas.id'], ),
    sa.ForeignKeyConstraint(['template_variable_id'], ['template_variables.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('faixa_id', 'template_variable_id')
    )
    op.create_table('telefones_invalidos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('faixa_id', sa.String(), nullable=False),
    sa.Column('codigo_cliente', sa.String(), nullable=False),
    sa.Column('celular_original', sa.String(), nullable=False),
    sa.Column('celular_normalizado', sa.String(), nullable=True),
    sa.Column('motivo', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['faixa_id'], ['faixas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telefones_invalidos_codigo_cliente'), 'telefones_invalidos', ['codigo_cliente'], unique=False)
    op.create_index(op.f('ix_telefones_invalidos_created_at'), 'telefones_invalidos', ['created_at'], unique=False)
    op.create_index(op.f('ix_telefones_invalidos_faixa_id'), 'telefones_invalidos', ['faixa_id'], unique=False)
    op.create_table('upload_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('faixa_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('uploaded_by', sa.String(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('accepted_count', sa.Integer(), nullable=False),
    sa.Column('rejected_count', sa.Integer(), nullable=False),
    sa.Column('invalid_phone_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['faixa_id'], ['faixas.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log_erros',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('faixa_id', sa.String(), nullable=True),
    sa.Column('queue_item_id', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['faixa_id'], ['faixas.id'], ),
    sa.ForeignKeyConstraint(['queue_item_id'], ['cobranca_fila.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log_erros')
    op.drop_table('upload_logs')
    op.drop_index(op.f('ix_telefones_invalidos_faixa_id'), table_name='telefones_invalidos')
    op.drop_index(op.f('ix_telefones_invalidos_created_at'), table_name='telefones_invalidos')
    op.drop_index(op.f('ix_telefones_invalidos_codigo_cliente'), table_name='telefones_invalidos')
    op.drop_table('telefones_invalidos')
    op.drop_table('faixa_variable_mappings')
    op.drop_table('faixa_numbers')
    op.drop_table('dispatch_configs')
    op.drop_index(op.f('ix_cobranca_fila_status'), table_name='cobranca_fila')
    op.drop_index(op.f('ix_cobranca_fila_faixa_id'), table_name='cobranca_fila')
    op.drop_index(op.f('ix_cobranca_fila_codigo_cliente'), table_name='cobranca_fila')
    op.drop_index(op.f('ix_cobranca_fila_celular'), table_name='cobranca_fila')
    op.drop_table('cobranca_fila')
    op.drop_table('template_variables')
    op.drop_index(op.f('ix_faixas_name'), table_name='faixas')
    op.drop_table('faixas')
    op.drop_index(op.f('ix_whatsapp_numbers_waba_id'), table_name='whatsapp_numbers')
    op.drop_index(op.f('ix_whatsapp_numbers_phone_number_id'), table_name='whatsapp_numbers')
    op.drop_table('whatsapp_numbers')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_templates_name'), table_name='templates')
    op.drop_table('templates')
    # ### end Alembic commands ###

    # drop_table não derruba o tipo ENUM nativo do Postgres por trás das
    # colunas Enum (ele pode, em tese, ser reaproveitado por outra tabela) —
    # sem isso, rodar upgrade novamente falha com "type already exists".
    bind = op.get_bind()
    sa.Enum(name='templateheadertype').drop(bind, checkfirst=True)
    sa.Enum(name='templatestatus').drop(bind, checkfirst=True)
    sa.Enum(name='queuestatus').drop(bind, checkfirst=True)
