"""is_admin em users

Revision ID: 657a127e9ad1
Revises: f1a2b3c4d5e6
Create Date: 2026-09-22 18:46:05.395711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '657a127e9ad1'
down_revision: Union[str, None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default só na criação da coluna, pra preencher as linhas que já
    # existem (o admin criado antes desta migration) sem quebrar o NOT NULL;
    # removido em seguida pra bater com o model, que não declara default no
    # banco (só no lado do Python).
    op.add_column(
        'users', sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.false())
    )
    op.alter_column('users', 'is_admin', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
