"""orcamento mensal

Revision ID: 6969f017649b
Revises: f3ff41b9d56e
Create Date: 2026-09-22 23:40:42.001623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6969f017649b'
down_revision: Union[str, None] = 'f3ff41b9d56e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orcamento_mensal',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('valor_orcado', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ano', 'mes', name='uq_orcamento_ano_mes')
    )
    op.create_index(op.f('ix_orcamento_mensal_ano'), 'orcamento_mensal', ['ano'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orcamento_mensal_ano'), table_name='orcamento_mensal')
    op.drop_table('orcamento_mensal')
    # ### end Alembic commands ###
