"""waba do token da meta

Revision ID: 74dbb10dea64
Revises: ba4e54b737c3
Create Date: 2026-09-22 01:17:35.559975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74dbb10dea64'
down_revision: Union[str, None] = 'ba4e54b737c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meta_tokens', sa.Column('waba_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_meta_tokens_waba_id'), 'meta_tokens', ['waba_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meta_tokens_waba_id'), table_name='meta_tokens')
    op.drop_column('meta_tokens', 'waba_id')
    # ### end Alembic commands ###
