"""blacklist de clientes

Revision ID: 8033be63fc19
Revises: 3bd1d89aa92f
Create Date: 2026-09-21 20:41:34.639733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8033be63fc19'
down_revision: Union[str, None] = '3bd1d89aa92f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_clientes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('valor', sa.String(), nullable=False),
    sa.Column('motivo', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tipo', 'valor')
    )
    op.create_index(op.f('ix_blacklist_clientes_valor'), 'blacklist_clientes', ['valor'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blacklist_clientes_valor'), table_name='blacklist_clientes')
    op.drop_table('blacklist_clientes')
    # ### end Alembic commands ###
