"""campo sugerido em template_variables

Revision ID: 8d8ff2c09268
Revises: 74dbb10dea64
Create Date: 2026-09-22 07:33:21.954545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d8ff2c09268'
down_revision: Union[str, None] = '74dbb10dea64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('template_variables', sa.Column('campo_sugerido', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('template_variables', 'campo_sugerido')
    # ### end Alembic commands ###
