"""lead_parcelas

Revision ID: ba4e54b737c3
Revises: e114e1769d8e
Create Date: 2026-09-21 23:25:51.015100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba4e54b737c3'
down_revision: Union[str, None] = 'e114e1769d8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_parcelas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('lead_id', sa.String(), nullable=False),
    sa.Column('titulo_codigo', sa.String(), nullable=False),
    sa.Column('empresa', sa.String(), nullable=False),
    sa.Column('vencimento', sa.Date(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('valor_cobrar', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lead_id', 'titulo_codigo')
    )
    op.create_index(op.f('ix_lead_parcelas_lead_id'), 'lead_parcelas', ['lead_id'], unique=False)
    op.create_index(op.f('ix_lead_parcelas_titulo_codigo'), 'lead_parcelas', ['titulo_codigo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lead_parcelas_titulo_codigo'), table_name='lead_parcelas')
    op.drop_index(op.f('ix_lead_parcelas_lead_id'), table_name='lead_parcelas')
    op.drop_table('lead_parcelas')
    # ### end Alembic commands ###
