"""leads

Revision ID: c79e2c254d00
Revises: 8033be63fc19
Create Date: 2026-09-21 21:17:55.133466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c79e2c254d00'
down_revision: Union[str, None] = '8033be63fc19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('codigo_cliente', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cpf', sa.String(), nullable=True),
    sa.Column('celular', sa.String(), nullable=True),
    sa.Column('celular_origem', sa.String(), nullable=True),
    sa.Column('celular_original', sa.String(), nullable=True),
    sa.Column('cluster', sa.String(), nullable=False),
    sa.Column('faixa', sa.String(), nullable=False),
    sa.Column('faixa_compra', sa.String(), nullable=True),
    sa.Column('qtd_compras', sa.Integer(), nullable=False),
    sa.Column('dias_atraso', sa.Integer(), nullable=False),
    sa.Column('qtd_parcelas', sa.Integer(), nullable=False),
    sa.Column('valor_em_aberto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('valor_cobrar', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('vencimento_mais_antigo', sa.Date(), nullable=False),
    sa.Column('lojas', sa.String(), nullable=False),
    sa.Column('portadores', sa.String(), nullable=False),
    sa.Column('status_cliente', sa.String(), nullable=False),
    sa.Column('spc_restricao', sa.String(), nullable=False),
    sa.Column('spc_data_consulta', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('cobrado_em', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_cliente', 'faixa', 'vencimento_mais_antigo')
    )
    op.create_index(op.f('ix_leads_cluster'), 'leads', ['cluster'], unique=False)
    op.create_index(op.f('ix_leads_codigo_cliente'), 'leads', ['codigo_cliente'], unique=False)
    op.create_index(op.f('ix_leads_created_at'), 'leads', ['created_at'], unique=False)
    op.create_index(op.f('ix_leads_faixa'), 'leads', ['faixa'], unique=False)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_faixa'), table_name='leads')
    op.drop_index(op.f('ix_leads_created_at'), table_name='leads')
    op.drop_index(op.f('ix_leads_codigo_cliente'), table_name='leads')
    op.drop_index(op.f('ix_leads_cluster'), table_name='leads')
    op.drop_table('leads')
    # ### end Alembic commands ###
