"""adiciona reserva_vazio em faixa_variable_mappings

Revision ID: dd623d789df7
Revises: e6b2d8f4a1c7
Create Date: 2026-10-08 12:06:14.374607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd623d789df7'
down_revision: Union[str, None] = 'e6b2d8f4a1c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faixa_variable_mappings', sa.Column('reserva_vazio', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('faixa_variable_mappings', 'reserva_vazio')
    # ### end Alembic commands ###
