"""meta_tokens e chatwoot_inbox_id

Revision ID: e114e1769d8e
Revises: 3ac8de259402
Create Date: 2026-09-21 23:28:23.291975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e114e1769d8e'
down_revision: Union[str, None] = '3ac8de259402'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meta_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('token_cifrado', sa.String(), nullable=False),
    sa.Column('ultimos4', sa.String(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('whatsapp_numbers', sa.Column('meta_token_id', sa.String(), nullable=True))
    op.add_column('whatsapp_numbers', sa.Column('chatwoot_inbox_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_whatsapp_numbers_meta_token_id_meta_tokens', 'whatsapp_numbers', 'meta_tokens', ['meta_token_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_whatsapp_numbers_meta_token_id_meta_tokens', 'whatsapp_numbers', type_='foreignkey')
    op.drop_column('whatsapp_numbers', 'chatwoot_inbox_id')
    op.drop_column('whatsapp_numbers', 'meta_token_id')
    op.drop_table('meta_tokens')
    # ### end Alembic commands ###
